version: "3.8"

services:
  vpn_bot:
    build: .
    container_name: vpn_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - bot_data:/app/data
      - bot_backups:/app/backups
    networks:
      - vpn_network

volumes:
  bot_data:
    name: vpn_bot_data
  bot_backups:
    name: vpn_bot_backups

networks:
  vpn_network:
    name: vpn_network
    driver: bridge
